# Generated by Django 3.2.7 on 2021-09-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='f_ingreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='f_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='i_genero',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='n_apellido1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='n_apellido2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='n_departamento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='n_municipio',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='n_nombres',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='o_cargo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='o_imagen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='o_jefe',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='o_numero',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='o_telefono',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='o_zona',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='v_ventas2019',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
